language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
install:
  - if [[ !($TRAVIS_PYTHON_VERSION == 3 && DJANGO_VERSION == 1.4) ]]; then pip install -q Django==$DJANGO_VERSION && python setup.py -q install; fi
script:
  - if [[ !($TRAVIS_PYTHON_VERSION == 3 && DJANGO_VERSION == 1.4) ]]; then python setup.py test; fi
